// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../repository/mocks/mock_repository.go -package=mocks OrganizationRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "TestHitalent2/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepositoryInterface is a mock of OrganizationRepositoryInterface interface.
type MockOrganizationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryInterfaceMockRecorder is the mock recorder for MockOrganizationRepositoryInterface.
type MockOrganizationRepositoryInterfaceMockRecorder struct {
	mock *MockOrganizationRepositoryInterface
}

// NewMockOrganizationRepositoryInterface creates a new mock instance.
func NewMockOrganizationRepositoryInterface(ctrl *gomock.Controller) *MockOrganizationRepositoryInterface {
	mock := &MockOrganizationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepositoryInterface) EXPECT() *MockOrganizationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockOrganizationRepositoryInterface) CreateDepartment(department *models.Department) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", department)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) CreateDepartment(department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).CreateDepartment), department)
}

// CreateEmployee mocks base method.
func (m *MockOrganizationRepositoryInterface) CreateEmployee(employee *models.Employee) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", employee)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) CreateEmployee(employee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).CreateEmployee), employee)
}

// DeleteDepartmentCascade mocks base method.
func (m *MockOrganizationRepositoryInterface) DeleteDepartmentCascade(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartmentCascade", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartmentCascade indicates an expected call of DeleteDepartmentCascade.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) DeleteDepartmentCascade(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartmentCascade", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).DeleteDepartmentCascade), id)
}

// DeleteDepartmentReassign mocks base method.
func (m *MockOrganizationRepositoryInterface) DeleteDepartmentReassign(id, intReassignToDepartmentId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartmentReassign", id, intReassignToDepartmentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartmentReassign indicates an expected call of DeleteDepartmentReassign.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) DeleteDepartmentReassign(id, intReassignToDepartmentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartmentReassign", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).DeleteDepartmentReassign), id, intReassignToDepartmentId)
}

// DepartmentExists mocks base method.
func (m *MockOrganizationRepositoryInterface) DepartmentExists(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepartmentExists", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DepartmentExists indicates an expected call of DepartmentExists.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) DepartmentExists(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepartmentExists", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).DepartmentExists), id)
}

// DepartmentNameExistsInParent mocks base method.
func (m *MockOrganizationRepositoryInterface) DepartmentNameExistsInParent(name string, parentID *int, excludeID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepartmentNameExistsInParent", name, parentID, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DepartmentNameExistsInParent indicates an expected call of DepartmentNameExistsInParent.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) DepartmentNameExistsInParent(name, parentID, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepartmentNameExistsInParent", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).DepartmentNameExistsInParent), name, parentID, excludeID)
}

// GetChildrenByParentID mocks base method.
func (m *MockOrganizationRepositoryInterface) GetChildrenByParentID(id int, includeEmployees bool) ([]*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildrenByParentID", id, includeEmployees)
	ret0, _ := ret[0].([]*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildrenByParentID indicates an expected call of GetChildrenByParentID.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetChildrenByParentID(id, includeEmployees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildrenByParentID", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetChildrenByParentID), id, includeEmployees)
}

// GetDepartment mocks base method.
func (m *MockOrganizationRepositoryInterface) GetDepartment(id int, includeEmployees bool) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", id, includeEmployees)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetDepartment(id, includeEmployees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetDepartment), id, includeEmployees)
}

// IsChildOf mocks base method.
func (m *MockOrganizationRepositoryInterface) IsChildOf(departmentID, parentID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChildOf", departmentID, parentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsChildOf indicates an expected call of IsChildOf.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) IsChildOf(departmentID, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChildOf", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).IsChildOf), departmentID, parentID)
}

// PatchDepartment mocks base method.
func (m *MockOrganizationRepositoryInterface) PatchDepartment(department *models.Department) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchDepartment", department)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchDepartment indicates an expected call of PatchDepartment.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) PatchDepartment(department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchDepartment", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).PatchDepartment), department)
}
