// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=../service/mocks/mock_service.go -package=mocks OrganizationServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "TestHitalent2/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationServiceInterface is a mock of OrganizationServiceInterface interface.
type MockOrganizationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockOrganizationServiceInterfaceMockRecorder is the mock recorder for MockOrganizationServiceInterface.
type MockOrganizationServiceInterfaceMockRecorder struct {
	mock *MockOrganizationServiceInterface
}

// NewMockOrganizationServiceInterface creates a new mock instance.
func NewMockOrganizationServiceInterface(ctrl *gomock.Controller) *MockOrganizationServiceInterface {
	mock := &MockOrganizationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationServiceInterface) EXPECT() *MockOrganizationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockOrganizationServiceInterface) CreateDepartment(department *models.Department) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", department)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockOrganizationServiceInterfaceMockRecorder) CreateDepartment(department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockOrganizationServiceInterface)(nil).CreateDepartment), department)
}

// CreateEmployee mocks base method.
func (m *MockOrganizationServiceInterface) CreateEmployee(employee *models.Employee, id string) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", employee, id)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockOrganizationServiceInterfaceMockRecorder) CreateEmployee(employee, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockOrganizationServiceInterface)(nil).CreateEmployee), employee, id)
}

// DeleteDepartment mocks base method.
func (m *MockOrganizationServiceInterface) DeleteDepartment(id, mode, reassignToDepartmentId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", id, mode, reassignToDepartmentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockOrganizationServiceInterfaceMockRecorder) DeleteDepartment(id, mode, reassignToDepartmentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockOrganizationServiceInterface)(nil).DeleteDepartment), id, mode, reassignToDepartmentId)
}

// GetDepartment mocks base method.
func (m *MockOrganizationServiceInterface) GetDepartment(id, depth, includeEmployees string) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", id, depth, includeEmployees)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockOrganizationServiceInterfaceMockRecorder) GetDepartment(id, depth, includeEmployees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockOrganizationServiceInterface)(nil).GetDepartment), id, depth, includeEmployees)
}

// PatchDepartment mocks base method.
func (m *MockOrganizationServiceInterface) PatchDepartment(id string, department *models.UpdateDepartmentRequest) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchDepartment", id, department)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchDepartment indicates an expected call of PatchDepartment.
func (mr *MockOrganizationServiceInterfaceMockRecorder) PatchDepartment(id, department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchDepartment", reflect.TypeOf((*MockOrganizationServiceInterface)(nil).PatchDepartment), id, department)
}
